name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 3.0.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  # Plugin for parsing html
  html: ">=0.15.0 <1.0.0"

  # Plugins for parsing css
  csslib: ^1.0.0

  # Plugins for rendering the <table> tag.
  flutter_layout_grid: ^2.0.4

  # Plugins for rendering the <video> tag.
  video_player: ">=2.1.1 <3.0.0"
  # chewie:
  #   path: /Users/qonvexmacmini/Desktop/chewie

  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^4.2.4

  # Plugins for rendering the <audio> tag.
  chewie_audio: ">=1.2.0 <2.0.0"

  # Plugins for rendering the <svg> tag.
  flutter_svg: ^2.0.0+1

  # Plugin for rendering MathML
  flutter_math_fork: ^0.7.1

  # plugin for firstWhereOrNull extension on lists
  collection: ">=1.15.0 <2.0.0"

  # plugin to convert integers to numerals
  numerus: ^2.1.2

  flutter:
    sdk: flutter
  chewie:
    git: https://github.com/alnaughty/chewie_custom.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
